### PR TITLE
add delexif, test.jpg

### LINKED ISSUE #4: 이미지 메타데이터 관리
이미지에 저장된 메타데이터 삭제 및 수정하는 기능

### PR DESCRIPTION
**Pull request by suppressor6**
closes #4

### CODE REVIEW

**Comment by rlaehdrbb** [comment]
closed #2

**Comment by GarlicCook** [comment]
LGTM

**Comment by rlaehdrbb** [comment]
LGTM

**Comment by rlaehdrbb** [comment]
LGTM

**Pull request merged**
